import FullBody from "./full-body.jpg";
import Dp from "./dp.jpg";
import GoogleCalander from "./calendar.png";
import warp from "./warp.svg";
import notion from "./notion.png";
import vscode from "./vscode.svg";
import obsidian from "./obsidian-icon.png";
import spotify from "./spotify.png";
import chatGPT from "./chatgpt-icon.svg";
import framer from "./framer.svg";
import drive from "./drive.png";
export { FullBody, Dp, GoogleCalander, warp, notion, vscode, obsidian, chatGPT, spotify, framer, drive };
